apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: soccersite-api
  name: soccersite-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soccersite-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: soccersite-api
    spec:
      containers:
      - image: denzelawuah/soccersite-api:0.0.3-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: soccersite-api-service
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: soccersite-api
  name: soccersite-api
  namespace: default
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: soccersite-api
  sessionAffinity: None
  type: LoadBalancer